# Generated by Django 2.2 on 2022-03-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maindishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sidedishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=50)),
                ('maindishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Maindishes')),
            ],
        ),
        migrations.CreateModel(
            name='Desserts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=50)),
                ('maindishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Maindishes')),
            ],
        ),
    ]
