# Generated by Django 2.2 on 2022-03-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField(max_length=100)),
                ('maindishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Maindishes')),
            ],
        ),
    ]
